call plug#begin()
" Bundles
" Plug 'ctrlpvim/ctrlp.vim'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'tomtom/tcomment_vim'
Plug 'jiangmiao/auto-pairs'
Plug 'ydzhou/simple-statusline.vim'
" Colorscheme
Plug 'ydzhou/monocolor.vim'
Plug 'arcticicestudio/nord-vim'
Plug 'NLKNguyen/papercolor-theme'
Plug 'sainnhe/everforest'
call plug#end()

set nocompatible
set mouse=a
set backspace=indent,eol,start
set gcr=a:blinkon0
set autoread
set noeb vb t_vb=
if has('autocmd')
	autocmd GUIEnter * set visualbell t_vb=
endif
set encoding=UTF-8
" Show completion candidates for vim commands
set wildmenu
set nofoldenable

filetype on
filetype plugin on
filetype indent on

set wrap lbr
set display=lastline
set tabstop=4 shiftwidth=4 softtabstop=4 expandtab shiftround
set showmatch matchtime=1 matchpairs&
set cindent autoindent
set clipboard+=unnamed

set number
set signcolumn=number

" set ruler
set laststatus=2
set statusline=%!SimStatusline()

syntax on
if has("gui_running")
    if has("mac")
        set guioptions-=m
        set guioptions-=r
        set guifont=Menlo:h16
    else
        set guifont=monospace\ 12
    endif
	set guioptions-=T
	set guioptions-=e
	set guioptions-=L
	set lines=50
	set columns=150
    set linespace=2
	colorscheme monocolor
    autocmd InsertEnter,InsertLeave * set cul!
else
    let &t_SI = "\e[6 q"
    let &t_EI = "\e[2 q"
    " Fix Kitty issue with vim colorscheme background
    let &t_ut = ''
	set t_Co=256
	set background=dark
	colorscheme everforest
endif

set incsearch ignorecase smartcase

""Backup
set noswapfile
set backupdir=~/.vim/backup

let mapleader=","
map ; <C-d>
map ' <C-u>
map <silent> <Leader>, <C-o>
map <silent> <Leader>. <C-i>
" Disable mouse double clicking for accidentally switching to visual mode
map <2-LeftMouse> <Nop>
" standard keys for wrapped lines
set whichwrap+=<,>,[,]
nnoremap j gj
nnoremap k gk
vnoremap j gj
vnoremap k gk
"" easier moving of code block
vnoremap < <gv
vnoremap > >gv
" Paste from 0 register to avoid cannot paste after deletion
nnoremap d "_d
xnoremap d "_d
nnoremap x "_x
xnoremap x "_x
nnoremap s "_s
xnoremap s "_s

autocmd BufNewFile,BufReadPost *.md set filetype=markdown

" Quickfix window auto close when closing a window
autocmd WinEnter * if winnr('$') == 1 && getbufvar(winbufnr(winnr()), "&buftype") == "quickfix"|q|endif

""""""""""""""""""""""""""
"" PLUGINS

" source ~/dotfiles/vim/configs/lspcomp.vim
" source ~/dotfiles/vim/configs/fern.vim
" source ~/dotfiles/vim/configs/ctrlp.vim
" source ~/dotfiles/vim/configs/vimdirvish.vim
source ~/dotfiles/vim/configs/fzf.vim
" source ~/dotfiles/vim/configs/startify.vim
" source ~/dotfiles/vim/configs/startify_quotes.vim

" TComment
"let g:tcommentOptions = {'whitespace' : 'no'}
map <silent> <Leader>c :TComment<CR>
