autocmd! bufwritepost .vimrc source %

se nocompatible
set mouse=a
set backspace=indent,eol,start
set gcr=a:blinkon0
set autoread
set noeb vb t_vb=
if has('autocmd')
	autocmd GUIEnter * set visualbell t_vb=
endif

set wrap
set lbr
set display=lastline
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set cindent
set autoindent
set ignorecase
set hlsearch
set clipboard+=unnamed

""Folding
set nofoldenable
"set foldmethod=indent
"set foldlevel=0
"set foldnestmax=1
"set foldcolumn=4
"autocmd BufEnter,BufCreate *.h,*.c,*cpp setlocal foldmethod=syntax
"noremap <space> za

""set ruler
set laststatus=2
set statusline=[%03l,%03v][%p%%]\ %=%F%m%r%h%w%<\ [%{&ff}:%{&fenc!=''?&fenc:&enc}]\ [%Y]

syntax on
if has("gui_running")
	if has("mac")
		"set noantialias
		set number
		"set guifont=AnonymousPro:h16
        "set guifont=Menlo:h14
		"set guifont=Monaco:h14
		"set guifont=PragmataPro:h16
        "set guifont=SourceCodePro-Regular:h16
        "set guifont=CourierNewPSMT:h16
		set printfont=h11 ""Print Font
		set linespace=4
		set guioptions-=r
		set guioptions-=T
		set guioptions-=e
		set guioptions-=L
		set lines=36
		set columns=100
		"set background=dark
		"colorscheme iceberg
		"colorscheme mac_classic
		"colorscheme zenburn
        "let moria_monochrome = 1
		"colorscheme moria
		"colorscheme birds_of_paradise
		colorscheme monocolor
		map <D-1> :set co=90<CR> 
		"map <D-2> :set co=120<CR>:winc =<CR> 
		map <D-2> :set co=120<CR>
		map <D-3> :set co=150<CR>
		map <D-d> :maca toggleFileBrowser:<CR>
        autocmd InsertEnter,InsertLeave * set cul!
	endif
else
	set guioptions-=e
	set t_Co=256
	set number
	set background=dark
	"colorscheme moria256
	"colorscheme xoria256-pluk
	colorscheme monocolor
	"colorscheme mac_classic
	"colorscheme vgod
    autocmd InsertEnter,InsertLeave * set cul!
endif

set incsearch
set hlsearch
set ignorecase
set smartcase

""Backup
set noswapfile
set backupdir=~/.vim/backup

let mapleader=","
map ; <C-d>
map ' <C-u>
"" standard keys for wrapped lines
set whichwrap+=<,>,[,]
nnoremap j gj
nnoremap k gk
vnoremap j gj
vnoremap k gk
nnoremap <Down> gj
nnoremap <Up> gk
vnoremap <Down> gj
vnoremap <Up> gk
inoremap <Down> <C-o>gj
inoremap <Up> <C-o>gk
"" map sort function to a key
vnoremap <Leader>s :sort<CR>
"" easier moving of code block
vnoremap < <gv
vnoremap > >gv

" Automatically open, but do not go to (if there are errors) the quickfix /
" location list window, or close it when is has become empty.
"
" Note: Must allow nesting of autocmds to enable any customizations for quickfix
" buffers.
" Note: Normally, :cwindow jumps to the quickfix window if the command opens it
" (but not if it's already open). However, as part of the autocmd, this doesn't
" seem to happen.
"autocmd QuickFixCmdPost [^l]* nested cwindow
"autocmd QuickFixCmdPost    l* nested lwindow
autocmd WinEnter * if winnr('$') == 1 && getbufvar(winbufnr(winnr()), "&buftype") == "quickfix"|q|endif

""""""""""""""""""""""""""
"" LANGUAGES CUSTOMIZATION
filetype on
filetype plugin on
filetype indent on

if !filereadable(expand("%:p:h")."/Makefile")
	autocmd	BufEnter,BufCreate *.cpp setlocal makeprg=g++\ -Wall\ -o\ %<\ %
	autocmd BufEnter,BufCreate *.c setlocal makeprg=gcc\ -Wall\ -o\ %<\ %
endif
""""""""""""""""""""""""""
"" PLUGINS

"" A.vim switch between header and source file
nnoremap <C-a> :A<CR>

""tocmd vimenter * NERDTree
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
"map <silent> <C-n> :NERDTreeToggle<CR> 
let NERDTreeIgnore=['\.$','\.pyc$','\.swp$','\~$']
let g:NERDTreeMouseMode=3

map <silent> <C-n> :NERDTreeTabsToggle<CR>
let g:nerdtree_tabs_open_on_gui_startup=0

" CtrlP
let g:ctrlp_map = '<leader>.'
let g:ctrlp_working_path_mode = 'ra'
set wildignore+=*/Movies/*,*Pictures/*,*/Music/*,*/Library/*,*/tmp/*,*.so,*.o,*.a,*.obj,*.swp,*.zip,*.pyc,*.pyo,*.class,.DS_Store
let g:ctrlp_custom_ignore = '\.git$\|\.hg$\|\.svn$\|\.rvm$'
let g:ctrlp_max_height=15

" TComment
let g:tcommentOptions = {'whitespace' : 'no'}
map <silent> <Leader>c :TComment<CR>
