(defun ar/show-welcome-buffer ()
  "Show *Welcome* buffer."
  (with-current-buffer (get-buffer-create "*Welcome*")
    (setq truncate-lines t)
    (let* ((buffer-read-only)
      (image-path "~/.emacs.d/emacs-e-logo.png")
      (image (create-image image-path))
      (size (image-size image))
      (height (cdr size))
      (width (car size))
      (top-margin (floor (/ (- (window-height) height) 2)))
      (left-margin (floor (/ (- (window-width) width) 2)))
      (prompt-title "Type q to exit"))
      (erase-buffer)
      (setq mode-line-format nil)
      (goto-char (point-min))
      (insert (make-string top-margin ?\n ))
      (insert (make-string left-margin ?\ ))
      (insert-image image)
      (insert "\n\n\n")
      (insert (make-string (floor (/ (- (window-width) (string-width prompt-title)) 2)) ?\ ))
      (insert prompt-title))
    (setq cursor-type nil)
    (read-only-mode +1)
    (switch-to-buffer (current-buffer))
    (local-set-key (kbd "q") 'kill-this-buffer)))

(when (< (length command-line-args) 2)
  (add-hook 'emacs-startup-hook
            (lambda () (when (display-graphic-p) (ar/show-welcome-buffer)))))

(provide 'splash-init)
